### ISSUE TITLE
error 429 too many request

### ISSUE THREAD

**Issue by jeromeborg** [unlikenesses/sanctum-react-spa#1]
Hye, I followed your tutorial on laravel new, thanks this is exactly what I was looking for.
I have a good level in laravel but not in react, I just have a 429 error, too many requests. By placing an earpiece in laravel, I saw that the book page constantly calls the api. I increased the "throtlle" in laravel, but can't we block the call to the API in the Book.js component?
Thank you

**Comment by rgruberski** [comment]
Check #2 , this small change should help

**Comment by AHS12** [comment]
`React.useEffect(() => {
        if (props.loggedIn) {
            apiClient.get('/api/book')
            .then(response => {
                setBooks(response.data)
            })
            .catch(error => console.error(error));
        }
    }, [props.loggedIn]);`

I changed my Book.js like this and now it is fixed

**Comment by jeromeborg** [comment]
Thanks
